import ModAB
import Lean.Util.CollectAxioms

open Lean Elab Command

run_cmd do
  let declarations : Array Name := #[
    ``ModAB.Binary64.pow_value,
    ``ModAB.Binary64.round_representable,
    ``ModAB.Binary64.round_exact,
    ``ModAB.Binary64.round_monotone,
    ``ModAB.Binary64.power_representable,
    ``ModAB.Binary64.round_zero,
    ``ModAB.Binary64.round_one,
    ``ModAB.Binary64.round_two,
    ``ModAB.Binary64.round_half,
    ``ModAB.Binary64.round_quarter,
    ``ModAB.Binary64.round_neg_exact,
    ``ModAB.Binary64.round_neg_one,
    ``ModAB.Binary64.round_neg_two,
    ``ModAB.Binary64.round_neg_half,
    ``ModAB.Binary64.round_interval,
    ``ModAB.Binary64.round_abs_le_one,
    ``ModAB.Binary64.round_abs_le_two,
    ``ModAB.Binary64.round_error,
    ``ModAB.Binary64.round_finite,
    ``ModAB.Binary64.epsilon_power,
    ``ModAB.Binary64.round_epsilon,
    ``ModAB.Binary64.gap_below_one,
    ``ModAB.Binary64.exact_half_of_ge_epsilon,
    ``ModAB.Binary64.factor_halving_exact,
    ``ModAB.Source.guard_literal,
    ``ModAB.Source.guard_exact,
    ``ModAB.Source.decision_switch_iff,
    ``ModAB.Source.decision_no_switch_iff,
    ``ModAB.Source.binary64_certified_switch,
    ``ModAB.Source.binary64_certified_no_switch,
    ``ModAB.Source.binary64_margin_guarantees,
    ``ModAB.Source.guardWord_valid,
    ``ModAB.Source.guardWord_value,
    ``ModAB.Source.decisionWord_refines,
    ``ModAB.Source.executable_switch_sound,
    ``ModAB.Source.executable_no_switch_sound,
    ``ModAB.IEEE64.one_valid,
    ``ModAB.IEEE64.one_value,
    ``ModAB.IEEE64.two_valid,
    ``ModAB.IEEE64.two_value,
    ``ModAB.IEEE64.abs_value,
    ``ModAB.IEEE64.min_valid,
    ``ModAB.IEEE64.max_valid,
    ``ModAB.IEEE64.expression_refines,
    ``ModAB.IEEE64.descriptor_round,
    ``ModAB.IEEE64.descriptor_max,
    ``ModAB.IEEE64.two_le_max,
    ``ModAB.IEEE64.add_refines,
    ``ModAB.IEEE64.sub_refines,
    ``ModAB.IEEE64.mul_refines,
    ``ModAB.IEEE64.div_refines,
    ``ModAB.Binary64.abs_le_two_of_unit,
    ``ModAB.Binary64.abs_le_two_of_half,
    ``ModAB.Binary64.factor_ranges,
    ``ModAB.Binary64.opposite_sum_bound,
    ``ModAB.Binary64.round_signs,
    ``ModAB.Binary64.concrete_gap_error,
    ``ModAB.Source.input_facts,
    ``ModAB.Source.source_eq_trace,
    ``ModAB.Source.source_safe,
    ``ModAB.Source.source_word_refines,
    ``ModAB.Source.source_error,
    ``ModAB.Source.binary64_program_error,
    ``ModAB.within_refl,
    ``ModAB.within_trans,
    ``ModAB.within_add,
    ``ModAB.within_sub,
    ``ModAB.within_abs,
    ``ModAB.within_half,
    ``ModAB.within_mono,
    ``ModAB.product_error,
    ``ModAB.square_error,
    ``ModAB.kappa_identity,
    ``ModAB.kappa_lipschitz,
    ``ModAB.ratio_range,
    ``ModAB.quotient_error,
    ``ModAB.factor_error,
    ``ModAB.scaled_errors,
    ``ModAB.guard_positive,
    ``ModAB.guard_negative,
    ``ModAB.complete_positive,
    ``ModAB.complete_negative,
    ``ModAB.certified_switch,
    ``ModAB.certified_no_switch,
    ``ModAB.binary64Epsilon_pos,
    ``ModAB.binary64_guard_value,
    ``ModAB.normalization_identity,
    ``ModAB.normalization_sign,
    ``ModAB.endpoint_ratio,
    ``ModAB.endpoint_rho_range,
    ``ModAB.endpoint_factor,
    ``ModAB.normalized_midpoint_bound,
    ``ModAB.scaled_original_switch,
    ``ModAB.subnormal_exact_scaled_gap,
    ``ModAB.subnormal_margin,
    ``ModAB.symmetric_exact_gap,
    ``ModAB.inputScale_pos,
    ``ModAB.normalized_input_bounds,
    ``ModAB.certified_from_residuals,
    ``ModAB.scaled_margin_guarantees,
    ``ModAB.unscaled_coefficient,
    ``ModAB.unscaled_error_budget
  ]
  let allowed : Array Name := #[``propext, ``Classical.choice, ``Quot.sound]
  for name in declarations do
    let dependencies ← Lean.collectAxioms name
    for dependency in dependencies do
      unless allowed.contains dependency do
        throwError "Unexpected axiom {dependency} in {name}"
    logInfo m!"{name}: {dependencies}"
  logInfo m!"PASS: {declarations.size} declarations; only standard logical axioms."
