name = "modab_switching"
version = "0.2.0"
defaultTargets = ["ModAB"]

[[lean_lib]]
name = "ModAB"

[[require]]
name = "floatlib"
git = "https://github.com/lean-dojo/FloatLib.git"
rev = "1e83f09ed8c41a953cf8f93d26c210778177b94a"
